---
apiVersion: v1
kind: Service
metadata:
 name: code-server
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      initContainers:
      # This container clones the desired git repo to the pvc volume. We're also going to chown the disk in case it got mounted as another user.
      - name: git-clone
        image: my-dockerhub-username/code-server
        command:
          - bash
        args:
          - -c
          - "sudo chown -R coder:coder /home/coder/scratch && git clone https://github.com/spring-projects/spring-petclinic.git /home/coder/scratch/spring-petclinic" 
        volumeMounts:
          - name: code-server-pv-claim
            mountPath: /home/coder/scratch
      containers:
      - image: my-dockerhub-username/code-server
        imagePullPolicy: Always
        name: code-server
        args: ["/home/coder/scratch/spring-petclinic/"]
        env:
        - name: PASSWORD
          value: "some-password-you'll-remember"
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: code-server-pv-claim
          mountPath: /home/coder/scratch
      volumes:
      - name: code-server-pv-claim
        persistentVolumeClaim:
          claimName: code-server-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi