---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: code-server
  namespace: code-server
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  tls: 
  - secretName: code-server
    hosts:
    - code-server.my-domain.com
  rules:
  - host: code-server.my-domain.com
    http:
      paths:
      - backend:
          serviceName: code-server
          servicePort: 8080